### PR TITLE
Add WasherDryer implementation (closes #101)

### LINKED ISSUE #101: Add WasherDryer implementation
https://developer.home-connect.com/docs/washer-dryer/supported_programs_and_options

### PR DESCRIPTION
**Pull request by yusijs**
PR to resolve #101

### CODE REVIEW

**Comment by DavidMStraub** [comment]
Great!

Why don't you submit this directly to HA core as well?

**Comment by yusijs** [comment]
I'm planning to, but this just implements the bare minimum required to make it equal to washers and dryers - I want to look more at the API docs to see if it's possible to make the programs connected (where it will do wash&dry in same cycle)

**Comment by VVlasy** [comment]
When will this be submitted to HA Core?

**Comment by DavidMStraub** [comment]
https://github.com/DavidMStraub/homeassistant-homeconnect/issues/126#issuecomment-832431788

Mostly waiting for testing feedback as I don't have one.

**Pull request merged**
